name: Tests Only

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Run Unit Tests
      run: |
        dotnet restore CampusConnect.Server.Tests/CampusConnect.Server.Tests.csproj
        dotnet test CampusConnect.Server.Tests/CampusConnect.Server.Tests.csproj --verbosity normal --filter "FullyQualifiedName!~Integration"
    
    - name: Test Summary
      run: echo "Unit tests completed successfully"